name: Client Build
on:
    workflow_call:
        inputs:
            environment:
                type: string

jobs:
    build-and-push-docker-image:
        runs-on: ubuntu-24.04

        steps:
            - name: Login to DockerHub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build image and push httpd
              uses: docker/build-push-action@v6
              with:
                  context: ./Client/
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-client:latest
                  push: ${{ github.ref == 'refs/heads/main' }}
